edition: 1.0.0
name: dcc-workflow-editor
access: default

vars:
  region: "cn-hangzhou"
  dcc_service:
    name: "dcc-workflow-editor"
    description: "Serverless Devs Website Service"

services:
  dcc-workflow-editor: # 业务名称/模块名称
    component: fc # 组件名称
    actions:
      pre-deploy:
        - component: fc build --use-docker --dockerfile ./Dockerfile
    props: # 组件的属性值
      region: ${vars.region}
      service: ${vars.dcc_service}
      function:
        name: "dcc-workflow-editor-func"
        description: "Serverless Devs Website Docusaurus Function"
        caPort: 9000
        memorySize: 512
        timeout: 30
        environmentVariables:
          CHAT_AGENT_BASE_URL: https://chat-story-func-chat-st-service-dtweumqpxw.us-west-1.fcapp.run
        runtime: custom-container
        customContainerConfig:
          image: "registry.cn-hangzhou.aliyuncs.com/dcc-cloud/dcc_workflow_editor:0.0.1"
        codeUri: ./
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              methods:
                - GET
                - POST